

CC=gcc
ACROSS_COMPILE=arm-buildroot-linux-gnueabihf-

all:
	$(CC) -o Pthread_Text1 Pthread_Text1.c -lpthread
	$(CC) -o Pthread_Text2 Pthread_Text2.c -lpthread
	$(CC) -o Pthread_Text3 Pthread_Text3.c -lpthread
	$(CC) -o Pthread_Text4 Pthread_Text4.c -lpthread
	$(CC) -o Pthread_Text5 Pthread_Text5.c -lpthread
	$(CC) -o Pthread_Text6 Pthread_Text6.c -lpthread
	$(CC) -o Pthread_Text7 Pthread_Text7.c -lpthread
	$(CC) -o Pthread_Text8 Pthread_Text8.c -lpthread
	$(CC) -o Pthread_Text9 Pthread_Text9.c -lpthread
	$(CC) -o Pthread_Text10 Pthread_Text10.c -lpthread
	$(CC) -o Pthread_Text11 Pthread_Text11.c -lpthread
	$(CC) -o Pthread_Text12 Pthread_Text12.c -lpthread

	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text1 Pthread_Text1.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text2 Pthread_Text2.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text3 Pthread_Text3.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text4 Pthread_Text4.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text5 Pthread_Text5.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text6 Pthread_Text6.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text7 Pthread_Text7.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text8 Pthread_Text8.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text9 Pthread_Text9.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text10 Pthread_Text10.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text11 Pthread_Text11.c -lpthread
	$(ACROSS_COMPILE)$(CC) -o imx6ull_Pthread_Text12 Pthread_Text12.c -lpthread

clean:
	rm -f Pthread_Text1
	rm -f Pthread_Text2
	rm -f Pthread_Text3
	rm -f Pthread_Text4
	rm -f Pthread_Text5
	rm -f Pthread_Text6
	rm -f Pthread_Text7
	rm -f Pthread_Text8
	rm -f Pthread_Text9
	rm -f Pthread_Text10
	rm -f Pthread_Text11
	rm -f Pthread_Text12

	rm -f imx6ull_Pthread_Text1
	rm -f imx6ull_Pthread_Text2
	rm -f imx6ull_Pthread_Text3
	rm -f imx6ull_Pthread_Text4
	rm -f imx6ull_Pthread_Text5
	rm -f imx6ull_Pthread_Text6
	rm -f imx6ull_Pthread_Text7
	rm -f imx6ull_Pthread_Text8
	rm -f imx6ull_Pthread_Text9
	rm -f imx6ull_Pthread_Text10
	rm -f imx6ull_Pthread_Text11
	rm -f imx6ull_Pthread_Text12